### ISSUE TITLE
Question about delete BN

### ISSUE THREAD

**Issue by baoyufuyou** [andyzeng/arc-robot-vision#8]
Hallo Zeng,
Can I ask a question about deleting BN. Why do you want to delete all of BN of pre-trained Resnet and transform into spatialconstdiagnal? 
And whats inn package? 
Is inn.ConstAffine like https://github.com/szagoruyko/imagine-nn/blob/master/ConstAffine.lua?
and what have been done in innutils.BNtoFixed?
I have't used torch, so i have so many question. Thanks a lot and Happy Easter!
 
````-- all BN modules in ResNet to be transformed into SpatialConstDiagonal
````-- (with inn routines)
````local inn = require 'inn'
````local innutils = require 'inn.utils'
````if not nn.SpatialConstDiagonal then
````  torch.class('nn.SpatialConstDiagonal', 'inn.ConstAffine')
````end
````utils.BNtoFixed = innutils.BNtoFixed

**Comment by wenjie23** [comment]
I am also wondering the purpose of 'Remove BN'?

If I understand the lua code correctly, why the running_mean and running_var are also freezed?
